setupVersion: 2
modelRoles:
  default: opencode-go/muse-spark-1.3-contributor:xhigh
  smol: opencode-go/deepseek-v4.1-flash:max
  slow: opencode-go/muse-spark-1.3-contributor:xhigh
  vision: opencode-go/deepseek-v4.1-flash:max
  plan: opencode-go/muse-spark-1.3-contributor:xhigh
  commit: opencode-go/deepseek-v4.1-flash:high
  tiny: opencode-go/deepseek-v4.1-flash:high
  memory: opencode-go/deepseek-v4.1-flash:high
  task: opencode-go/muse-spark-1.3-contributor:xhigh
  advisor: opencode-go/muse-spark-1.3-contributor:xhigh